#!/usr/bin/bash

ldconfig -m /lib
ldconfig -m /usr/lib
ldconfig -m /usr/lib/fakeroot
ldconfig -m /usr/lib/pth
ldconfig -m /usr/local/lib
ldconfig -32 -m /usr/lib32
# seems to be necessary for gcc to find the libraries
#ldconfig -m /usr/lib32
ldconfig -R
ldconfig -32 -R
